# Generated by Django 5.0.1 on 2024-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_task_prioity_task_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2024-01-09 14:30'),
            preserve_default=False,
        ),
    ]
