# Generated by Django 5.0.1 on 2024-01-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staus',
            field=models.CharField(choices=[('p', 'pause'), ('i', 'in Progress'), ('c', 'complete')], default='pause', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('l', 'low'), ('m', 'medium'), ('h', 'high')], max_length=30),
        ),
    ]
